import { ALL_FIELDS_GROUP, defineType } from "sanity"

import { listingPreview } from "./shared"

import {
  addressField,
  buildingYearField,
  carBoxField,
  cityField,
  countryField,
  climateControlField,
  commercialAreaSqmField,
  conciergeServiceField,
  condoFeesField,
  descriptionField,
  energyClassField,
  excerptField,
  floorField,
  floorPlansField,
  furnishingField,
  galleryImagesField,
  gardenField,
  hasAccessibleAccessField,
  hasAlarmSystemField,
  hasAtticRoomField,
  hasBalconyField,
  hasCellarField,
  hasTavernField,
  hasTennisCourtField,
  hasTerraceField,
  heatingField,
  isArchivedField,
  listingTitleField,
  mapField,
  mainImageField,
  positionInfoField,
  listingContractTypeField,
  listingSearchTokensField,
  parkingSpacesField,
  priceField,
  poolField,
  postalCodeField,
  provinceField,
} from "../fields"

export const listingResidential = defineType({
  name: "listingResidential",
  title: "Residenziale",
  type: "document",
  groups: [
    { name: "propertySheet", title: "Scheda immobile", default: true },
    { name: "optionals", title: "Campi opzionali" },
    { name: "location", title: "Località" },
    { name: "mapPosition", title: "Mappa e posizione" },
    { name: "content", title: "Contenuto" },
    { name: "floorPlans", title: "Planimetrie" },
    { ...ALL_FIELDS_GROUP, hidden: true },
  ],
  fields: [
    /* Scheda immobile */
    isArchivedField({ group: "propertySheet" }),
    listingContractTypeField({ required: true, group: "propertySheet" }),
    listingSearchTokensField({ group: "propertySheet" }),
    priceField({ group: "propertySheet" }),
    commercialAreaSqmField({ required: true, group: "propertySheet" }),
    condoFeesField({ required: true, group: "propertySheet" }),
    floorField({ required: true, group: "propertySheet" }),
    conciergeServiceField({ required: true, group: "propertySheet" }),
    buildingYearField({ required: true, group: "propertySheet" }),
    heatingField({ required: true, group: "propertySheet" }),
    energyClassField({ required: true, group: "propertySheet" }),
    /* Località */
    countryField({ required: true, group: "location" }),
    provinceField({ required: true, group: "location" }),
    cityField({ required: true, group: "location" }),
    addressField({ group: "location" }),
    postalCodeField({ group: "location" }),
    mapField({ group: "mapPosition" }),
    positionInfoField({ group: "mapPosition" }),
    /* Contenuto */
    listingTitleField({ group: "content" }),
    mainImageField({ required: true, group: "content" }),
    galleryImagesField({ group: "content" }),
    excerptField({ group: "content" }),
    descriptionField({ group: "content" }),
    /* Planimetrie */
    floorPlansField({ group: "floorPlans" }),
    /* Campi opzionali */
    furnishingField({ group: "optionals" }),
    gardenField({ group: "optionals" }),
    carBoxField({ group: "optionals" }),
    parkingSpacesField({ group: "optionals" }),
    hasBalconyField({ group: "optionals" }),
    hasTerraceField({ group: "optionals" }),
    hasCellarField({ group: "optionals" }),
    hasAtticRoomField({ group: "optionals" }),
    hasTavernField({ group: "optionals" }),
    hasAlarmSystemField({ group: "optionals" }),
    poolField({ group: "optionals" }),
    hasTennisCourtField({ group: "optionals" }),
    hasAccessibleAccessField({ group: "optionals" }),
    climateControlField({ group: "optionals" }),
  ],
  preview: listingPreview(),
})
