import { ALL_FIELDS_GROUP, defineType } from "sanity"

import { listingPreview } from "./shared"

import {
  addressField,
  cityField,
  countryField,
  climateControlField,
  commercialAreaSqmField,
  customSpecificationsField,
  descriptionField,
  energyClassField,
  excerptField,
  floorPlansField,
  galleryImagesField,
  hasAccessibleAccessField,
  hasAccessibleRestroomField,
  hasFireProtectionSystemField,
  hasFlueField,
  hasAlarmSystemField,
  hasDrivewayAccessField,
  hasLoadingUnloadingField,
  hasTennisCourtField,
  heatingField,
  isArchivedField,
  listingContractTypeField,
  listingSearchTokensField,
  listingTitleField,
  mapField,
  mainImageField,
  parkingSpacesField,
  priceField,
  poolField,
  postalCodeField,
  provinceField,
  outdoorAreaSqmField,
  roomCountField,
} from "../fields"

export const listingHospitality = defineType({
  name: "listingHospitality",
  title: "Hospitality",
  type: "document",
  groups: [
    { name: "propertySheet", title: "Scheda immobile", default: true },
    { name: "optionals", title: "Campi opzionali" },
    { name: "location", title: "Località" },
    { name: "content", title: "Contenuto" },
    { name: "floorPlans", title: "Planimetrie" },
    { ...ALL_FIELDS_GROUP, hidden: true },
  ],
  fields: [
    /* Scheda immobile */
    isArchivedField({ group: "propertySheet" }),
    listingContractTypeField({ required: true, group: "propertySheet" }),
    listingSearchTokensField({ group: "propertySheet" }),
    priceField({ group: "propertySheet" }),
    commercialAreaSqmField({ required: true, group: "propertySheet" }),
    roomCountField({ required: true, group: "propertySheet" }),
    energyClassField({ required: true, group: "propertySheet" }),
    /* Località */
    countryField({ required: true, group: "location" }),
    provinceField({ required: true, group: "location" }),
    cityField({ required: true, group: "location" }),
    addressField({ group: "location" }),
    postalCodeField({ group: "location" }),
    mapField({ group: "location" }),
    /* Contenuto */
    listingTitleField({ group: "content" }),
    mainImageField({ required: true, group: "content" }),
    galleryImagesField({ group: "content" }),
    excerptField({ group: "content" }),
    descriptionField({ group: "content" }),
    /* Planimetrie */
    floorPlansField({ group: "floorPlans" }),
    /* Campi opzionali */
    hasAccessibleRestroomField({ group: "optionals" }),
    hasFlueField({ group: "optionals" }),
    hasFireProtectionSystemField({ group: "optionals" }),
    hasLoadingUnloadingField({ group: "optionals" }),
    hasDrivewayAccessField({ group: "optionals" }),
    parkingSpacesField({ group: "optionals" }),
    hasAlarmSystemField({ group: "optionals" }),
    hasAccessibleAccessField({ group: "optionals" }),
    climateControlField({ group: "optionals" }),
    outdoorAreaSqmField({ group: "optionals" }),
    heatingField({ group: "optionals" }),
    poolField({ group: "optionals" }),
    hasTennisCourtField({ group: "optionals" }),
    customSpecificationsField({ group: "optionals" }),
  ],
  preview: listingPreview(),
})
