/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type ListingShopsAndOffices = {
  _id: string
  _type: "listingShopsAndOffices"
  _createdAt: string
  _updatedAt: string
  _rev: string
  shopsAndOfficesTypology?: "shops" | "offices"
  commercialAreaSqm?: number
  floor?:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "other"
    | "underground"
    | "semiUnderground"
    | "groundFloor"
    | "raisedGroundFloor"
    | "multiLevel"
    | "penthouse"
    | "topFloor"
    | "attic"
    | "entireBuilding"
  displayWindows?: string
  conciergeService?: "fullDay" | "halfDay" | "none"
  buildingYear?: number
  heating?: {
    heatingType?: "autonomous" | "centralized" | "other"
    heatingOther?: string
  }
  energyClass?: {
    energyClassScheme?:
      | "notClassifiable"
      | "inProgress"
      | "dl192_2005"
      | "law90_2013"
    energyClassRatingDl192?: "A+" | "A" | "B" | "C" | "D" | "E" | "F" | "G"
    energyClassRatingLaw90?:
      | "A4"
      | "A3"
      | "A2"
      | "A1"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
  }
  country?: "IT" | "FR" | "CH" | "DE" | "AT" | "ES" | "GB" | "US"
  province?:
    | "AG"
    | "AL"
    | "AN"
    | "AR"
    | "AP"
    | "AT"
    | "AV"
    | "BA"
    | "BT"
    | "BL"
    | "BN"
    | "BG"
    | "BI"
    | "BO"
    | "BZ"
    | "BS"
    | "BR"
    | "CA"
    | "CL"
    | "CB"
    | "CE"
    | "CT"
    | "CZ"
    | "CH"
    | "CO"
    | "CS"
    | "CR"
    | "KR"
    | "CN"
    | "EN"
    | "FM"
    | "FE"
    | "FI"
    | "FG"
    | "FC"
    | "FR"
    | "GE"
    | "GO"
    | "GR"
    | "IM"
    | "IS"
    | "AQ"
    | "SP"
    | "LT"
    | "LE"
    | "LC"
    | "LI"
    | "LO"
    | "LU"
    | "MC"
    | "MN"
    | "MS"
    | "MT"
    | "ME"
    | "MI"
    | "MO"
    | "MB"
    | "NA"
    | "NO"
    | "NU"
    | "OR"
    | "PD"
    | "PA"
    | "PR"
    | "PV"
    | "PG"
    | "PU"
    | "PE"
    | "PC"
    | "PI"
    | "PT"
    | "PN"
    | "PZ"
    | "PO"
    | "RG"
    | "RA"
    | "RC"
    | "RE"
    | "RI"
    | "RN"
    | "RM"
    | "RO"
    | "SA"
    | "SS"
    | "SV"
    | "SI"
    | "SR"
    | "SO"
    | "SU"
    | "TA"
    | "TE"
    | "TR"
    | "TO"
    | "TP"
    | "TN"
    | "TV"
    | "TS"
    | "UD"
    | "AO"
    | "VA"
    | "VB"
    | "VC"
    | "VE"
    | "VR"
    | "VV"
    | "VI"
    | "VT"
  city?: string
  address?: {
    streetName?: string
    streetNumber?: string
  }
  postalCode?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: LocalizedString
    _type: "image"
  }
  description?: LocalizedPortableText
  excerpt?: LocalizedText
  floorPlans?: Array<{
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
    _key: string
  }>
  furnishing?:
    | "furnished"
    | "unfurnished"
    | "partiallyFurnished"
    | "kitchenOnlyFurnished"
  hasAccessibleRestroom?: boolean
  hasFlue?: boolean
  hasFireProtectionSystem?: boolean
  hasLoadingUnloading?: boolean
  hasDrivewayAccess?: boolean
  parkingSpaces?: {
    choice?: "covered" | "uncovered" | "other"
    otherSpecification?: string
  }
  hasAlarmSystem?: boolean
  hasAccessibleAccess?: boolean
  climateControl?: "autonomous" | "centralized" | "preInstallation"
  conciergeServiceShops?: "fullDay" | "halfDay" | "none"
  officeLayout?: {
    choice?: "openSpace" | "individualOffices" | "other"
    otherSpecification?: string
  }
  condoFees?: {
    condoFeesAmount?: number
    condoFeesCurrency?: "EUR" | "CHF"
  }
}

export type LocalizedText = {
  _type: "localizedText"
  it?: string
  en?: string
}

export type LocalizedPortableText = {
  _type: "localizedPortableText"
  it?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  en?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
}

export type LocalizedString = {
  _type: "localizedString"
  it?: string
  en?: string
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type ListingCountryHouses = {
  _id: string
  _type: "listingCountryHouses"
  _createdAt: string
  _updatedAt: string
  _rev: string
  countryHouseTypology?: "sea" | "lakesAndCountryside" | "mountain"
  commercialAreaSqm?: number
  floor?:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "other"
    | "underground"
    | "semiUnderground"
    | "groundFloor"
    | "raisedGroundFloor"
    | "multiLevel"
    | "penthouse"
    | "topFloor"
    | "attic"
    | "entireBuilding"
  buildingYear?: number
  heating?: {
    heatingType?: "autonomous" | "centralized" | "other"
    heatingOther?: string
  }
  energyClass?: {
    energyClassScheme?:
      | "notClassifiable"
      | "inProgress"
      | "dl192_2005"
      | "law90_2013"
    energyClassRatingDl192?: "A+" | "A" | "B" | "C" | "D" | "E" | "F" | "G"
    energyClassRatingLaw90?:
      | "A4"
      | "A3"
      | "A2"
      | "A1"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
  }
  country?: "IT" | "FR" | "CH" | "DE" | "AT" | "ES" | "GB" | "US"
  province?:
    | "AG"
    | "AL"
    | "AN"
    | "AR"
    | "AP"
    | "AT"
    | "AV"
    | "BA"
    | "BT"
    | "BL"
    | "BN"
    | "BG"
    | "BI"
    | "BO"
    | "BZ"
    | "BS"
    | "BR"
    | "CA"
    | "CL"
    | "CB"
    | "CE"
    | "CT"
    | "CZ"
    | "CH"
    | "CO"
    | "CS"
    | "CR"
    | "KR"
    | "CN"
    | "EN"
    | "FM"
    | "FE"
    | "FI"
    | "FG"
    | "FC"
    | "FR"
    | "GE"
    | "GO"
    | "GR"
    | "IM"
    | "IS"
    | "AQ"
    | "SP"
    | "LT"
    | "LE"
    | "LC"
    | "LI"
    | "LO"
    | "LU"
    | "MC"
    | "MN"
    | "MS"
    | "MT"
    | "ME"
    | "MI"
    | "MO"
    | "MB"
    | "NA"
    | "NO"
    | "NU"
    | "OR"
    | "PD"
    | "PA"
    | "PR"
    | "PV"
    | "PG"
    | "PU"
    | "PE"
    | "PC"
    | "PI"
    | "PT"
    | "PN"
    | "PZ"
    | "PO"
    | "RG"
    | "RA"
    | "RC"
    | "RE"
    | "RI"
    | "RN"
    | "RM"
    | "RO"
    | "SA"
    | "SS"
    | "SV"
    | "SI"
    | "SR"
    | "SO"
    | "SU"
    | "TA"
    | "TE"
    | "TR"
    | "TO"
    | "TP"
    | "TN"
    | "TV"
    | "TS"
    | "UD"
    | "AO"
    | "VA"
    | "VB"
    | "VC"
    | "VE"
    | "VR"
    | "VV"
    | "VI"
    | "VT"
  city?: string
  address?: {
    streetName?: string
    streetNumber?: string
  }
  postalCode?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: LocalizedString
    _type: "image"
  }
  description?: LocalizedPortableText
  excerpt?: LocalizedText
  floorPlans?: Array<{
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
    _key: string
  }>
  outdoorAreaSqm?: number
  furnishing?:
    | "furnished"
    | "unfurnished"
    | "partiallyFurnished"
    | "kitchenOnlyFurnished"
  garden?: "private" | "shared" | "privateAndShared"
  carBox?: {
    choice?: "single" | "double" | "other"
    otherSpecification?: string
  }
  parkingSpaces?: {
    choice?: "covered" | "uncovered" | "other"
    otherSpecification?: string
  }
  hasBalcony?: boolean
  hasTerrace?: boolean
  hasCellar?: boolean
  hasAtticRoom?: boolean
  hasTavern?: boolean
  hasAlarmSystem?: boolean
  pool?: "yes" | "condominium"
  hasTennisCourt?: boolean
  hasAccessibleAccess?: boolean
  climateControl?: "autonomous" | "centralized" | "preInstallation"
  condoFees?: {
    condoFeesAmount?: number
    condoFeesCurrency?: "EUR" | "CHF"
  }
}

export type ListingResidential = {
  _id: string
  _type: "listingResidential"
  _createdAt: string
  _updatedAt: string
  _rev: string
  commercialAreaSqm?: number
  condoFees?: {
    condoFeesAmount?: number
    condoFeesCurrency?: "EUR" | "CHF"
  }
  floor?:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "other"
    | "underground"
    | "semiUnderground"
    | "groundFloor"
    | "raisedGroundFloor"
    | "multiLevel"
    | "penthouse"
    | "topFloor"
    | "attic"
    | "entireBuilding"
  conciergeService?: "fullDay" | "halfDay" | "none"
  buildingYear?: number
  heating?: {
    heatingType?: "autonomous" | "centralized" | "other"
    heatingOther?: string
  }
  energyClass?: {
    energyClassScheme?:
      | "notClassifiable"
      | "inProgress"
      | "dl192_2005"
      | "law90_2013"
    energyClassRatingDl192?: "A+" | "A" | "B" | "C" | "D" | "E" | "F" | "G"
    energyClassRatingLaw90?:
      | "A4"
      | "A3"
      | "A2"
      | "A1"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
  }
  country?: "IT" | "FR" | "CH" | "DE" | "AT" | "ES" | "GB" | "US"
  province?:
    | "AG"
    | "AL"
    | "AN"
    | "AR"
    | "AP"
    | "AT"
    | "AV"
    | "BA"
    | "BT"
    | "BL"
    | "BN"
    | "BG"
    | "BI"
    | "BO"
    | "BZ"
    | "BS"
    | "BR"
    | "CA"
    | "CL"
    | "CB"
    | "CE"
    | "CT"
    | "CZ"
    | "CH"
    | "CO"
    | "CS"
    | "CR"
    | "KR"
    | "CN"
    | "EN"
    | "FM"
    | "FE"
    | "FI"
    | "FG"
    | "FC"
    | "FR"
    | "GE"
    | "GO"
    | "GR"
    | "IM"
    | "IS"
    | "AQ"
    | "SP"
    | "LT"
    | "LE"
    | "LC"
    | "LI"
    | "LO"
    | "LU"
    | "MC"
    | "MN"
    | "MS"
    | "MT"
    | "ME"
    | "MI"
    | "MO"
    | "MB"
    | "NA"
    | "NO"
    | "NU"
    | "OR"
    | "PD"
    | "PA"
    | "PR"
    | "PV"
    | "PG"
    | "PU"
    | "PE"
    | "PC"
    | "PI"
    | "PT"
    | "PN"
    | "PZ"
    | "PO"
    | "RG"
    | "RA"
    | "RC"
    | "RE"
    | "RI"
    | "RN"
    | "RM"
    | "RO"
    | "SA"
    | "SS"
    | "SV"
    | "SI"
    | "SR"
    | "SO"
    | "SU"
    | "TA"
    | "TE"
    | "TR"
    | "TO"
    | "TP"
    | "TN"
    | "TV"
    | "TS"
    | "UD"
    | "AO"
    | "VA"
    | "VB"
    | "VC"
    | "VE"
    | "VR"
    | "VV"
    | "VI"
    | "VT"
  city?: string
  address?: {
    streetName?: string
    streetNumber?: string
  }
  postalCode?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: LocalizedString
    _type: "image"
  }
  description?: LocalizedPortableText
  excerpt?: LocalizedText
  floorPlans?: Array<{
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
    _key: string
  }>
  furnishing?:
    | "furnished"
    | "unfurnished"
    | "partiallyFurnished"
    | "kitchenOnlyFurnished"
  garden?: "private" | "shared" | "privateAndShared"
  carBox?: {
    choice?: "single" | "double" | "other"
    otherSpecification?: string
  }
  parkingSpaces?: {
    choice?: "covered" | "uncovered" | "other"
    otherSpecification?: string
  }
  hasBalcony?: boolean
  hasTerrace?: boolean
  hasCellar?: boolean
  hasAtticRoom?: boolean
  hasTavern?: boolean
  hasAlarmSystem?: boolean
  pool?: "yes" | "condominium"
  hasTennisCourt?: boolean
  hasAccessibleAccess?: boolean
  climateControl?: "autonomous" | "centralized" | "preInstallation"
}

export type TranslationMetadata = {
  _id: string
  _type: "translation.metadata"
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type SiteContentReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "siteContent"
}

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue"
  value?: SiteContentReference
  language: string
}

export type SiteContent = {
  _id: string
  _type: "siteContent"
  _createdAt: string
  _updatedAt: string
  _rev: string
  language?: string
  title: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | ListingShopsAndOffices
  | LocalizedText
  | LocalizedPortableText
  | LocalizedString
  | SanityImageCrop
  | SanityImageHotspot
  | ListingCountryHouses
  | ListingResidential
  | TranslationMetadata
  | InternationalizedArrayReference
  | SiteContentReference
  | InternationalizedArrayReferenceValue
  | SiteContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: src/sanity/lib/queries.ts
// Variable: SITE_CONTENT_QUERY
// Query: coalesce(    *[_type == "siteContent" && language == $locale][0]{ _id, title, language },    *[_type == "siteContent" && language == "it"][0]{ _id, title, language } // fallback to IT if missing  )
export type SITE_CONTENT_QUERY_RESULT =
  | {
      _id: string
      title: string
      language: "it"
    }
  | {
      _id: string
      title: string
      language: string | null
    }
  | null

// Source: src/sanity/lib/queries.ts
// Variable: LISTINGS_PREVIEW_QUERY
// Query: *[_type in [    "listingResidential",    "listingCountryHouses",    "listingShopsAndOffices"  ]] | order(_updatedAt desc) [0...10]{    ...,    mainImage {      ...,      asset->    },    floorPlans[]{      ...,      asset->    }  }
export type LISTINGS_PREVIEW_QUERY_RESULT = Array<
  | {
      _id: string
      _type: "listingCountryHouses"
      _createdAt: string
      _updatedAt: string
      _rev: string
      countryHouseTypology?: "lakesAndCountryside" | "mountain" | "sea"
      commercialAreaSqm?: number
      floor?:
        | "1"
        | "10"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "attic"
        | "entireBuilding"
        | "groundFloor"
        | "multiLevel"
        | "other"
        | "penthouse"
        | "raisedGroundFloor"
        | "semiUnderground"
        | "topFloor"
        | "underground"
      buildingYear?: number
      heating?: {
        heatingType?: "autonomous" | "centralized" | "other"
        heatingOther?: string
      }
      energyClass?: {
        energyClassScheme?:
          | "dl192_2005"
          | "inProgress"
          | "law90_2013"
          | "notClassifiable"
        energyClassRatingDl192?: "A" | "A+" | "B" | "C" | "D" | "E" | "F" | "G"
        energyClassRatingLaw90?:
          | "A1"
          | "A2"
          | "A3"
          | "A4"
          | "B"
          | "C"
          | "D"
          | "E"
          | "F"
          | "G"
      }
      country?: "AT" | "CH" | "DE" | "ES" | "FR" | "GB" | "IT" | "US"
      province?:
        | "AG"
        | "AL"
        | "AN"
        | "AO"
        | "AP"
        | "AQ"
        | "AR"
        | "AT"
        | "AV"
        | "BA"
        | "BG"
        | "BI"
        | "BL"
        | "BN"
        | "BO"
        | "BR"
        | "BS"
        | "BT"
        | "BZ"
        | "CA"
        | "CB"
        | "CE"
        | "CH"
        | "CL"
        | "CN"
        | "CO"
        | "CR"
        | "CS"
        | "CT"
        | "CZ"
        | "EN"
        | "FC"
        | "FE"
        | "FG"
        | "FI"
        | "FM"
        | "FR"
        | "GE"
        | "GO"
        | "GR"
        | "IM"
        | "IS"
        | "KR"
        | "LC"
        | "LE"
        | "LI"
        | "LO"
        | "LT"
        | "LU"
        | "MB"
        | "MC"
        | "ME"
        | "MI"
        | "MN"
        | "MO"
        | "MS"
        | "MT"
        | "NA"
        | "NO"
        | "NU"
        | "OR"
        | "PA"
        | "PC"
        | "PD"
        | "PE"
        | "PG"
        | "PI"
        | "PN"
        | "PO"
        | "PR"
        | "PT"
        | "PU"
        | "PV"
        | "PZ"
        | "RA"
        | "RC"
        | "RE"
        | "RG"
        | "RI"
        | "RM"
        | "RN"
        | "RO"
        | "SA"
        | "SI"
        | "SO"
        | "SP"
        | "SR"
        | "SS"
        | "SU"
        | "SV"
        | "TA"
        | "TE"
        | "TN"
        | "TO"
        | "TP"
        | "TR"
        | "TS"
        | "TV"
        | "UD"
        | "VA"
        | "VB"
        | "VC"
        | "VE"
        | "VI"
        | "VR"
        | "VT"
        | "VV"
      city?: string
      address?: {
        streetName?: string
        streetNumber?: string
      }
      postalCode?: string
      mainImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: LocalizedString
        _type: "image"
      } | null
      description?: LocalizedPortableText
      excerpt?: LocalizedText
      floorPlans: Array<{
        asset: {
          _id: string
          _type: "sanity.fileAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        _type: "file"
        _key: string
      }> | null
      outdoorAreaSqm?: number
      furnishing?:
        | "furnished"
        | "kitchenOnlyFurnished"
        | "partiallyFurnished"
        | "unfurnished"
      garden?: "private" | "privateAndShared" | "shared"
      carBox?: {
        choice?: "double" | "other" | "single"
        otherSpecification?: string
      }
      parkingSpaces?: {
        choice?: "covered" | "other" | "uncovered"
        otherSpecification?: string
      }
      hasBalcony?: boolean
      hasTerrace?: boolean
      hasCellar?: boolean
      hasAtticRoom?: boolean
      hasTavern?: boolean
      hasAlarmSystem?: boolean
      pool?: "condominium" | "yes"
      hasTennisCourt?: boolean
      hasAccessibleAccess?: boolean
      climateControl?: "autonomous" | "centralized" | "preInstallation"
      condoFees?: {
        condoFeesAmount?: number
        condoFeesCurrency?: "CHF" | "EUR"
      }
    }
  | {
      _id: string
      _type: "listingResidential"
      _createdAt: string
      _updatedAt: string
      _rev: string
      commercialAreaSqm?: number
      condoFees?: {
        condoFeesAmount?: number
        condoFeesCurrency?: "CHF" | "EUR"
      }
      floor?:
        | "1"
        | "10"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "attic"
        | "entireBuilding"
        | "groundFloor"
        | "multiLevel"
        | "other"
        | "penthouse"
        | "raisedGroundFloor"
        | "semiUnderground"
        | "topFloor"
        | "underground"
      conciergeService?: "fullDay" | "halfDay" | "none"
      buildingYear?: number
      heating?: {
        heatingType?: "autonomous" | "centralized" | "other"
        heatingOther?: string
      }
      energyClass?: {
        energyClassScheme?:
          | "dl192_2005"
          | "inProgress"
          | "law90_2013"
          | "notClassifiable"
        energyClassRatingDl192?: "A" | "A+" | "B" | "C" | "D" | "E" | "F" | "G"
        energyClassRatingLaw90?:
          | "A1"
          | "A2"
          | "A3"
          | "A4"
          | "B"
          | "C"
          | "D"
          | "E"
          | "F"
          | "G"
      }
      country?: "AT" | "CH" | "DE" | "ES" | "FR" | "GB" | "IT" | "US"
      province?:
        | "AG"
        | "AL"
        | "AN"
        | "AO"
        | "AP"
        | "AQ"
        | "AR"
        | "AT"
        | "AV"
        | "BA"
        | "BG"
        | "BI"
        | "BL"
        | "BN"
        | "BO"
        | "BR"
        | "BS"
        | "BT"
        | "BZ"
        | "CA"
        | "CB"
        | "CE"
        | "CH"
        | "CL"
        | "CN"
        | "CO"
        | "CR"
        | "CS"
        | "CT"
        | "CZ"
        | "EN"
        | "FC"
        | "FE"
        | "FG"
        | "FI"
        | "FM"
        | "FR"
        | "GE"
        | "GO"
        | "GR"
        | "IM"
        | "IS"
        | "KR"
        | "LC"
        | "LE"
        | "LI"
        | "LO"
        | "LT"
        | "LU"
        | "MB"
        | "MC"
        | "ME"
        | "MI"
        | "MN"
        | "MO"
        | "MS"
        | "MT"
        | "NA"
        | "NO"
        | "NU"
        | "OR"
        | "PA"
        | "PC"
        | "PD"
        | "PE"
        | "PG"
        | "PI"
        | "PN"
        | "PO"
        | "PR"
        | "PT"
        | "PU"
        | "PV"
        | "PZ"
        | "RA"
        | "RC"
        | "RE"
        | "RG"
        | "RI"
        | "RM"
        | "RN"
        | "RO"
        | "SA"
        | "SI"
        | "SO"
        | "SP"
        | "SR"
        | "SS"
        | "SU"
        | "SV"
        | "TA"
        | "TE"
        | "TN"
        | "TO"
        | "TP"
        | "TR"
        | "TS"
        | "TV"
        | "UD"
        | "VA"
        | "VB"
        | "VC"
        | "VE"
        | "VI"
        | "VR"
        | "VT"
        | "VV"
      city?: string
      address?: {
        streetName?: string
        streetNumber?: string
      }
      postalCode?: string
      mainImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: LocalizedString
        _type: "image"
      } | null
      description?: LocalizedPortableText
      excerpt?: LocalizedText
      floorPlans: Array<{
        asset: {
          _id: string
          _type: "sanity.fileAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        _type: "file"
        _key: string
      }> | null
      furnishing?:
        | "furnished"
        | "kitchenOnlyFurnished"
        | "partiallyFurnished"
        | "unfurnished"
      garden?: "private" | "privateAndShared" | "shared"
      carBox?: {
        choice?: "double" | "other" | "single"
        otherSpecification?: string
      }
      parkingSpaces?: {
        choice?: "covered" | "other" | "uncovered"
        otherSpecification?: string
      }
      hasBalcony?: boolean
      hasTerrace?: boolean
      hasCellar?: boolean
      hasAtticRoom?: boolean
      hasTavern?: boolean
      hasAlarmSystem?: boolean
      pool?: "condominium" | "yes"
      hasTennisCourt?: boolean
      hasAccessibleAccess?: boolean
      climateControl?: "autonomous" | "centralized" | "preInstallation"
    }
  | {
      _id: string
      _type: "listingShopsAndOffices"
      _createdAt: string
      _updatedAt: string
      _rev: string
      shopsAndOfficesTypology?: "offices" | "shops"
      commercialAreaSqm?: number
      floor?:
        | "1"
        | "10"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "attic"
        | "entireBuilding"
        | "groundFloor"
        | "multiLevel"
        | "other"
        | "penthouse"
        | "raisedGroundFloor"
        | "semiUnderground"
        | "topFloor"
        | "underground"
      displayWindows?: string
      conciergeService?: "fullDay" | "halfDay" | "none"
      buildingYear?: number
      heating?: {
        heatingType?: "autonomous" | "centralized" | "other"
        heatingOther?: string
      }
      energyClass?: {
        energyClassScheme?:
          | "dl192_2005"
          | "inProgress"
          | "law90_2013"
          | "notClassifiable"
        energyClassRatingDl192?: "A" | "A+" | "B" | "C" | "D" | "E" | "F" | "G"
        energyClassRatingLaw90?:
          | "A1"
          | "A2"
          | "A3"
          | "A4"
          | "B"
          | "C"
          | "D"
          | "E"
          | "F"
          | "G"
      }
      country?: "AT" | "CH" | "DE" | "ES" | "FR" | "GB" | "IT" | "US"
      province?:
        | "AG"
        | "AL"
        | "AN"
        | "AO"
        | "AP"
        | "AQ"
        | "AR"
        | "AT"
        | "AV"
        | "BA"
        | "BG"
        | "BI"
        | "BL"
        | "BN"
        | "BO"
        | "BR"
        | "BS"
        | "BT"
        | "BZ"
        | "CA"
        | "CB"
        | "CE"
        | "CH"
        | "CL"
        | "CN"
        | "CO"
        | "CR"
        | "CS"
        | "CT"
        | "CZ"
        | "EN"
        | "FC"
        | "FE"
        | "FG"
        | "FI"
        | "FM"
        | "FR"
        | "GE"
        | "GO"
        | "GR"
        | "IM"
        | "IS"
        | "KR"
        | "LC"
        | "LE"
        | "LI"
        | "LO"
        | "LT"
        | "LU"
        | "MB"
        | "MC"
        | "ME"
        | "MI"
        | "MN"
        | "MO"
        | "MS"
        | "MT"
        | "NA"
        | "NO"
        | "NU"
        | "OR"
        | "PA"
        | "PC"
        | "PD"
        | "PE"
        | "PG"
        | "PI"
        | "PN"
        | "PO"
        | "PR"
        | "PT"
        | "PU"
        | "PV"
        | "PZ"
        | "RA"
        | "RC"
        | "RE"
        | "RG"
        | "RI"
        | "RM"
        | "RN"
        | "RO"
        | "SA"
        | "SI"
        | "SO"
        | "SP"
        | "SR"
        | "SS"
        | "SU"
        | "SV"
        | "TA"
        | "TE"
        | "TN"
        | "TO"
        | "TP"
        | "TR"
        | "TS"
        | "TV"
        | "UD"
        | "VA"
        | "VB"
        | "VC"
        | "VE"
        | "VI"
        | "VR"
        | "VT"
        | "VV"
      city?: string
      address?: {
        streetName?: string
        streetNumber?: string
      }
      postalCode?: string
      mainImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: LocalizedString
        _type: "image"
      } | null
      description?: LocalizedPortableText
      excerpt?: LocalizedText
      floorPlans: Array<{
        asset: {
          _id: string
          _type: "sanity.fileAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        _type: "file"
        _key: string
      }> | null
      furnishing?:
        | "furnished"
        | "kitchenOnlyFurnished"
        | "partiallyFurnished"
        | "unfurnished"
      hasAccessibleRestroom?: boolean
      hasFlue?: boolean
      hasFireProtectionSystem?: boolean
      hasLoadingUnloading?: boolean
      hasDrivewayAccess?: boolean
      parkingSpaces?: {
        choice?: "covered" | "other" | "uncovered"
        otherSpecification?: string
      }
      hasAlarmSystem?: boolean
      hasAccessibleAccess?: boolean
      climateControl?: "autonomous" | "centralized" | "preInstallation"
      conciergeServiceShops?: "fullDay" | "halfDay" | "none"
      officeLayout?: {
        choice?: "individualOffices" | "openSpace" | "other"
        otherSpecification?: string
      }
      condoFees?: {
        condoFeesAmount?: number
        condoFeesCurrency?: "CHF" | "EUR"
      }
    }
>

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  coalesce(\n    *[_type == "siteContent" && language == $locale][0]{ _id, title, language },\n    *[_type == "siteContent" && language == "it"][0]{ _id, title, language } // fallback to IT if missing\n  )\n': SITE_CONTENT_QUERY_RESULT
    '\n  *[_type in [\n    "listingResidential",\n    "listingCountryHouses",\n    "listingShopsAndOffices"\n  ]] | order(_updatedAt desc) [0...10]{\n    ...,\n    mainImage {\n      ...,\n      asset->\n    },\n    floorPlans[]{\n      ...,\n      asset->\n    }\n  }\n': LISTINGS_PREVIEW_QUERY_RESULT
  }
}
