/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type ListingLand = {
  _id: string
  _type: "listingLand"
  _createdAt: string
  _updatedAt: string
  _rev: string
  listingLabel?: string
}

export type ListingHospitality = {
  _id: string
  _type: "listingHospitality"
  _createdAt: string
  _updatedAt: string
  _rev: string
  listingLabel?: string
}

export type ListingIndustrial = {
  _id: string
  _type: "listingIndustrial"
  _createdAt: string
  _updatedAt: string
  _rev: string
  listingLabel?: string
}

export type ListingOfficesAndRetail = {
  _id: string
  _type: "listingOfficesAndRetail"
  _createdAt: string
  _updatedAt: string
  _rev: string
  listingLabel?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type ListingCountryHouses = {
  _id: string
  _type: "listingCountryHouses"
  _createdAt: string
  _updatedAt: string
  _rev: string
  countryHouseTypology?: "sea" | "lakesAndCountryside" | "mountain"
  commercialAreaSqm?: number
  floor?:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "other"
    | "underground"
    | "semiUnderground"
    | "groundFloor"
    | "raisedGroundFloor"
    | "multiLevel"
    | "penthouse"
    | "topFloor"
    | "attic"
    | "entireBuilding"
  buildingYear?: number
  heating?: {
    heatingType?: "autonomous" | "centralized" | "other"
    heatingOther?: string
  }
  energyClass?: {
    energyClassScheme?:
      | "notClassifiable"
      | "inProgress"
      | "dl192_2005"
      | "law90_2013"
    energyClassRatingDl192?: "A+" | "A" | "B" | "C" | "D" | "E" | "F" | "G"
    energyClassRatingLaw90?:
      | "A4"
      | "A3"
      | "A2"
      | "A1"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
  }
  country?: "IT" | "FR" | "CH" | "DE" | "AT" | "ES" | "GB" | "US"
  province?:
    | "AG"
    | "AL"
    | "AN"
    | "AR"
    | "AP"
    | "AT"
    | "AV"
    | "BA"
    | "BT"
    | "BL"
    | "BN"
    | "BG"
    | "BI"
    | "BO"
    | "BZ"
    | "BS"
    | "BR"
    | "CA"
    | "CL"
    | "CB"
    | "CE"
    | "CT"
    | "CZ"
    | "CH"
    | "CO"
    | "CS"
    | "CR"
    | "KR"
    | "CN"
    | "EN"
    | "FM"
    | "FE"
    | "FI"
    | "FG"
    | "FC"
    | "FR"
    | "GE"
    | "GO"
    | "GR"
    | "IM"
    | "IS"
    | "AQ"
    | "SP"
    | "LT"
    | "LE"
    | "LC"
    | "LI"
    | "LO"
    | "LU"
    | "MC"
    | "MN"
    | "MS"
    | "MT"
    | "ME"
    | "MI"
    | "MO"
    | "MB"
    | "NA"
    | "NO"
    | "NU"
    | "OR"
    | "PD"
    | "PA"
    | "PR"
    | "PV"
    | "PG"
    | "PU"
    | "PE"
    | "PC"
    | "PI"
    | "PT"
    | "PN"
    | "PZ"
    | "PO"
    | "RG"
    | "RA"
    | "RC"
    | "RE"
    | "RI"
    | "RN"
    | "RM"
    | "RO"
    | "SA"
    | "SS"
    | "SV"
    | "SI"
    | "SR"
    | "SO"
    | "SU"
    | "TA"
    | "TE"
    | "TR"
    | "TO"
    | "TP"
    | "TN"
    | "TV"
    | "TS"
    | "UD"
    | "AO"
    | "VA"
    | "VB"
    | "VC"
    | "VE"
    | "VR"
    | "VV"
    | "VI"
    | "VT"
  city?: string
  address?: {
    streetName?: string
    streetNumber?: string
  }
  postalCode?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  excerpt?: string
  floorPlans?: Array<{
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
    _key: string
  }>
  outdoorAreaSqm?: number
  furnishing?:
    | "furnished"
    | "unfurnished"
    | "partiallyFurnished"
    | "kitchenOnlyFurnished"
  garden?: "private" | "shared" | "privateAndShared"
  carBox?: {
    choice?: "single" | "double" | "other"
    otherSpecification?: string
  }
  parkingSpaces?: {
    choice?: "covered" | "uncovered" | "other"
    otherSpecification?: string
  }
  hasBalcony?: boolean
  hasTerrace?: boolean
  hasCellar?: boolean
  hasAtticRoom?: boolean
  hasTavern?: boolean
  hasAlarmSystem?: boolean
  pool?: "yes" | "condominium"
  hasTennisCourt?: boolean
  hasAccessibleAccess?: boolean
  climateControl?: "autonomous" | "centralized" | "preInstallation"
  condoFees?: {
    condoFeesAmount?: number
    condoFeesCurrency?: "EUR" | "CHF"
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type ListingResidential = {
  _id: string
  _type: "listingResidential"
  _createdAt: string
  _updatedAt: string
  _rev: string
  commercialAreaSqm?: number
  condoFees?: {
    condoFeesAmount?: number
    condoFeesCurrency?: "EUR" | "CHF"
  }
  floor?:
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "other"
    | "underground"
    | "semiUnderground"
    | "groundFloor"
    | "raisedGroundFloor"
    | "multiLevel"
    | "penthouse"
    | "topFloor"
    | "attic"
    | "entireBuilding"
  conciergeService?: "fullDay" | "halfDay" | "none"
  buildingYear?: number
  heating?: {
    heatingType?: "autonomous" | "centralized" | "other"
    heatingOther?: string
  }
  energyClass?: {
    energyClassScheme?:
      | "notClassifiable"
      | "inProgress"
      | "dl192_2005"
      | "law90_2013"
    energyClassRatingDl192?: "A+" | "A" | "B" | "C" | "D" | "E" | "F" | "G"
    energyClassRatingLaw90?:
      | "A4"
      | "A3"
      | "A2"
      | "A1"
      | "B"
      | "C"
      | "D"
      | "E"
      | "F"
      | "G"
  }
  country?: "IT" | "FR" | "CH" | "DE" | "AT" | "ES" | "GB" | "US"
  province?:
    | "AG"
    | "AL"
    | "AN"
    | "AR"
    | "AP"
    | "AT"
    | "AV"
    | "BA"
    | "BT"
    | "BL"
    | "BN"
    | "BG"
    | "BI"
    | "BO"
    | "BZ"
    | "BS"
    | "BR"
    | "CA"
    | "CL"
    | "CB"
    | "CE"
    | "CT"
    | "CZ"
    | "CH"
    | "CO"
    | "CS"
    | "CR"
    | "KR"
    | "CN"
    | "EN"
    | "FM"
    | "FE"
    | "FI"
    | "FG"
    | "FC"
    | "FR"
    | "GE"
    | "GO"
    | "GR"
    | "IM"
    | "IS"
    | "AQ"
    | "SP"
    | "LT"
    | "LE"
    | "LC"
    | "LI"
    | "LO"
    | "LU"
    | "MC"
    | "MN"
    | "MS"
    | "MT"
    | "ME"
    | "MI"
    | "MO"
    | "MB"
    | "NA"
    | "NO"
    | "NU"
    | "OR"
    | "PD"
    | "PA"
    | "PR"
    | "PV"
    | "PG"
    | "PU"
    | "PE"
    | "PC"
    | "PI"
    | "PT"
    | "PN"
    | "PZ"
    | "PO"
    | "RG"
    | "RA"
    | "RC"
    | "RE"
    | "RI"
    | "RN"
    | "RM"
    | "RO"
    | "SA"
    | "SS"
    | "SV"
    | "SI"
    | "SR"
    | "SO"
    | "SU"
    | "TA"
    | "TE"
    | "TR"
    | "TO"
    | "TP"
    | "TN"
    | "TV"
    | "TS"
    | "UD"
    | "AO"
    | "VA"
    | "VB"
    | "VC"
    | "VE"
    | "VR"
    | "VV"
    | "VI"
    | "VT"
  city?: string
  address?: {
    streetName?: string
    streetNumber?: string
  }
  postalCode?: string
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  excerpt?: string
  floorPlans?: Array<{
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
    _key: string
  }>
  furnishing?:
    | "furnished"
    | "unfurnished"
    | "partiallyFurnished"
    | "kitchenOnlyFurnished"
  garden?: "private" | "shared" | "privateAndShared"
  carBox?: {
    choice?: "single" | "double" | "other"
    otherSpecification?: string
  }
  parkingSpaces?: {
    choice?: "covered" | "uncovered" | "other"
    otherSpecification?: string
  }
  hasBalcony?: boolean
  hasTerrace?: boolean
  hasCellar?: boolean
  hasAtticRoom?: boolean
  hasTavern?: boolean
  hasAlarmSystem?: boolean
  pool?: "yes" | "condominium"
  hasTennisCourt?: boolean
  hasAccessibleAccess?: boolean
  climateControl?: "autonomous" | "centralized" | "preInstallation"
}

export type SiteContent = {
  _id: string
  _type: "siteContent"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | ListingLand
  | ListingHospitality
  | ListingIndustrial
  | ListingOfficesAndRetail
  | SanityImageAssetReference
  | SanityFileAssetReference
  | ListingCountryHouses
  | SanityImageCrop
  | SanityImageHotspot
  | ListingResidential
  | SiteContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: src/sanity/lib/queries.ts
// Variable: SITE_CONTENT_QUERY
// Query: *[_type == "siteContent"] | order(_updatedAt desc) [0]{ _id, title }
export type SITE_CONTENT_QUERY_RESULT = {
  _id: string
  title: string
} | null

// Source: src/sanity/lib/queries.ts
// Variable: LISTINGS_PREVIEW_QUERY
// Query: *[_type in [    "listingResidential",    "listingCountryHouses",    "listingOfficesAndRetail",    "listingIndustrial",    "listingHospitality",    "listingLand"  ]] | order(_updatedAt desc) [0...10]{ _id, _type, listingLabel, commercialAreaSqm, floor }
export type LISTINGS_PREVIEW_QUERY_RESULT = Array<
  | {
      _id: string
      _type: "listingCountryHouses"
      listingLabel: null
      commercialAreaSqm: number | null
      floor:
        | "1"
        | "10"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "attic"
        | "entireBuilding"
        | "groundFloor"
        | "multiLevel"
        | "other"
        | "penthouse"
        | "raisedGroundFloor"
        | "semiUnderground"
        | "topFloor"
        | "underground"
        | null
    }
  | {
      _id: string
      _type: "listingHospitality"
      listingLabel: string | null
      commercialAreaSqm: null
      floor: null
    }
  | {
      _id: string
      _type: "listingIndustrial"
      listingLabel: string | null
      commercialAreaSqm: null
      floor: null
    }
  | {
      _id: string
      _type: "listingLand"
      listingLabel: string | null
      commercialAreaSqm: null
      floor: null
    }
  | {
      _id: string
      _type: "listingOfficesAndRetail"
      listingLabel: string | null
      commercialAreaSqm: null
      floor: null
    }
  | {
      _id: string
      _type: "listingResidential"
      listingLabel: null
      commercialAreaSqm: number | null
      floor:
        | "1"
        | "10"
        | "2"
        | "3"
        | "4"
        | "5"
        | "6"
        | "7"
        | "8"
        | "9"
        | "attic"
        | "entireBuilding"
        | "groundFloor"
        | "multiLevel"
        | "other"
        | "penthouse"
        | "raisedGroundFloor"
        | "semiUnderground"
        | "topFloor"
        | "underground"
        | null
    }
>

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteContent"] | order(_updatedAt desc) [0]{ _id, title }': SITE_CONTENT_QUERY_RESULT
    '*[_type in [\n    "listingResidential",\n    "listingCountryHouses",\n    "listingOfficesAndRetail",\n    "listingIndustrial",\n    "listingHospitality",\n    "listingLand"\n  ]] | order(_updatedAt desc) [0...10]{ _id, _type, listingLabel, commercialAreaSqm, floor }': LISTINGS_PREVIEW_QUERY_RESULT
  }
}
